Add worker groups with different settings
salsify/delayed_job_worker_pool pull request #7
Opened 2020-06-02 15:11 UTC by severinraez

A follow up to https://github.com/salsify/delayed_job_worker_pool/pull/3

I've changed the terminology to `worker_groups` so we have clear semantics. The worker pool are all the workers, a worker group is a subset of workers sharing the same options.

2020-06-02 17:50 UTC, jturkel requested changes
Overall looks good. Can we add some test coverage to `spec/delayed_job_worker_pool_spec.rb` to test the changes to `lib/delayed_job_worker_pool/worker_pool.rb`? I'm also curious to hear your thoughts on providing worker groups with names for better visibility into their state.

2020-06-02 17:50 UTC, jturkel commented on lib/delayed_job_worker_pool/dsl.rb
> +      pool_options = WorkerGroupOptions.new
Should this be `group_options` to follow consistent terminology?

2020-06-02 17:50 UTC, jturkel commented on lib/delayed_job_worker_pool/dsl.rb
> +    def assert_pools_defined!
Should this be `assert_groups_defined!` to follow consistent terminology?

2020-06-02 17:50 UTC, jturkel commented on lib/delayed_job_worker_pool/worker_group_options.rb
> +    ALL_SETTINGS.each { |setting| attr_accessor setting }
Minor but we can shorten this up a bit.

```suggestion
    attr_accessor *ALL_SETTINGS
```

2020-06-02 17:50 UTC, jturkel commented on lib/delayed_job_worker_pool/worker_pool.rb
> +      @worker_pid_options = {}
Can we combine the `@worker_pids` and `@worker_pid_options` data structures to make it easier to keep the information stored in them consistent?

2020-06-02 17:50 UTC, jturkel commented on lib/delayed_job_worker_pool/worker_pool.rb
>        log("Started worker #{worker_pid}")
Would it make sense to give worker groups names so we can include that information in log statements like this to provide visibility into which groups are churning workers?

2020-06-03 05:42 UTC, severinraez commented
Thanks for your review, @jturkel
I agree with all the points you raised. Worker group names will help a lot with knowing what's going on. In that spirit, I plan to also set the `name_prefix` (https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L33) of the DJ workers accordingly.

2020-06-04 13:20 UTC, severinraez commented
Hi @jturkel 

I've added two commits, handling everything but the worker names in the first and adding worker names in the second. Please have a look. I'd be happy to follow up on additional feedback if you have any and then squash the commits to allow for a clean merge.

2020-06-04 14:31 UTC, jturkel requested changes
Looking good! I like the extraction of the registry. Mostly minor feedback but the biggest question I have is whether we should have a default worker group name to remove some friction for the common scenario of a single worker pool.

2020-06-04 14:31 UTC, jturkel commented on README.md
> +worker_group(:my_group_name) do |g|
Should we make the group name optional with a reasonable default under the assumption that a single worker group will still be the most common use case for this gem?

2020-06-04 14:31 UTC, jturkel commented on lib/delayed_job_worker_pool/registry.rb
> +      @groups[group_name][:pids] << pid
Can we add error handling around a group not being found? Same applies to the `options` method.

2020-06-04 14:31 UTC, jturkel commented on lib/delayed_job_worker_pool/registry.rb
> +      @groups.values.map{ |v| v[:pids] }.flatten
```suggestion
      @groups.values.flat_map{ |v| v[:pids] }
```

2020-06-04 14:31 UTC, jturkel commented on lib/delayed_job_worker_pool/registry.rb
> +    def include?(pid)
Based on the name it wasn't clear to me if this was checking groups or workers. Should we call this `include_worker?` to make the intent more obvious?

2020-06-04 14:31 UTC, jturkel commented on lib/delayed_job_worker_pool/registry.rb
> +    def empty?
Similar comment as `include?` i.e. it wasn't clear to me if this was checking groups or workers. Should we call this `has_workers?` to make the intent more obvious?

2020-06-04 14:31 UTC, jturkel commented on spec/delayed_job_worker_pool/registry_spec.rb
> +describe DelayedJobWorkerPool::Registry do
Can we add test coverage for edge cases in this class e.g. duplicate group names, looking up workers that don't exists, etc.?

2020-06-04 14:31 UTC, jturkel commented on spec/delayed_job_worker_pool_spec.rb
> +      it_behaves_like 'runs jobs on active queues'
Do these tests need to make sure that each group is picking up jobs on the appropriate queues? It looks like it won't detect the scenario where worker groups are listening on all queues.

2020-06-08 09:34 UTC, severinraez commented
Thanks :) 

I've implemented your suggested changes. I've thought about a default worker group name before and went for explicit namings just to have a decision. You bringing this up too leads me to believe a default might be simpler.

I did not (yet?) add a test to `spec/delayed_job_worker_pool_spec.rb`. I had another look, my thinking here is as follows:

- The existing test makes sure no jobs queued on queue `inactive` are run - thus we can be sure no worker is working all queues. 
- Left unchecked is the following contrived edge case: If we'd somehow build a union of the specified per-worker group queues and passed that to each worker group, the test would be green. In `dsl_spec.rb` we already examine which worker groups get which options.

Thinking further, there's a whole class of checks we don't do around making sure the specified options are really passed through to the Delayed::Worker (`sleep_delay` and so on). Adding those would bloat `delayed_job_worker_pool_spec.rb`.

I think the proper way to do this would be to separate worker instantiation from forking and looking after children by refactoring `WorkerPool`, then having the worker instatiation part thoroughly tested (maybe by mocking `Delayed::Worker`).

Thus, I'd suggest we let the test be as is and merge this PR. I can open an issue summarizing the refactoring and opportunities more thorough testing if you're interested. I'm afraid I'll be too short on time to do this in the coming months. That being said, if you feel more confident with the "worker working all specified queues" also being tested, I can come up with a solution and add a commit.

2020-06-08 20:41 UTC, jturkel approved these changes
I think the test coverage is good enough for now. Thanks for all your work on this. I'll get it merged and released after you rebase/squash.

2020-06-16 06:47 UTC, severinraez commented
Thank you too for your guidance, that improved the quality a lot.

I've squashed and rebased :)

2020-06-16 13:01 UTC, jturkel approved these changes
Thanks for the contribution @severinraez! I'll release an updated version of the gem today.

2020-06-16 13:01 UTC, merged